/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsLogIdRouteImport } from './routes/logs/$logId'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId.edit'
import { Route as RolesRoleIdEditRouteImport } from './routes/roles/$roleId.edit'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdRoute = LogsLogIdRouteImport.update({
  id: '/logs/$logId',
  path: '/logs/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdEditRoute = RolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/applications': typeof ApplicationsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/logs/$logId'
    | '/patients/new'
    | '/roles/new'
    | '/users/new'
    | '/applications/'
    | '/logs/'
    | '/patients/'
    | '/roles/'
    | '/users/'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/logs/$logId'
    | '/patients/new'
    | '/roles/new'
    | '/users/new'
    | '/applications'
    | '/logs'
    | '/patients'
    | '/roles'
    | '/users'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/logs/$logId'
    | '/patients/new'
    | '/roles/new'
    | '/users/new'
    | '/applications/'
    | '/logs/'
    | '/patients/'
    | '/roles/'
    | '/users/'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  LogsLogIdRoute: typeof LogsLogIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  RolesNewRoute: typeof RolesNewRoute
  UsersNewRoute: typeof UsersNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  RolesRoleIdEditRoute: typeof RolesRoleIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId': {
      id: '/logs/$logId'
      path: '/logs/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId/edit': {
      id: '/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof RolesRoleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  LogsLogIdRoute: LogsLogIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  RolesNewRoute: RolesNewRoute,
  UsersNewRoute: UsersNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  RolesRoleIdEditRoute: RolesRoleIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
