/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AccessLogsIndexRouteImport } from './routes/access-logs/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as DeIdentifierIndexRouteImport } from './routes/de-identifier/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as IntakeIndexRouteImport } from './routes/intake/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsLogIdRouteImport } from './routes/logs/$logId'
import { Route as MetadataIndexRouteImport } from './routes/metadata/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as RejectionsIndexRouteImport } from './routes/rejections/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as Zone2InboxIndexRouteImport } from './routes/zone2-inbox/index'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId.edit'
import { Route as RolesRoleIdEditRouteImport } from './routes/roles/$roleId.edit'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessLogsIndexRoute = AccessLogsIndexRouteImport.update({
  id: '/access-logs/',
  path: '/access-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeIdentifierIndexRoute = DeIdentifierIndexRouteImport.update({
  id: '/de-identifier/',
  path: '/de-identifier/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdRoute = LogsLogIdRouteImport.update({
  id: '/logs/$logId',
  path: '/logs/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataIndexRoute = MetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectionsIndexRoute = RejectionsIndexRouteImport.update({
  id: '/rejections/',
  path: '/rejections/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const Zone2InboxIndexRoute = Zone2InboxIndexRouteImport.update({
  id: '/zone2-inbox/',
  path: '/zone2-inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdEditRoute = RolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/access-logs/': typeof AccessLogsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/de-identifier/': typeof DeIdentifierIndexRoute
  '/files/': typeof FilesIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rejections/': typeof RejectionsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/zone2-inbox/': typeof Zone2InboxIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/access-logs': typeof AccessLogsIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/de-identifier': typeof DeIdentifierIndexRoute
  '/files': typeof FilesIndexRoute
  '/intake': typeof IntakeIndexRoute
  '/logs': typeof LogsIndexRoute
  '/metadata': typeof MetadataIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/rejections': typeof RejectionsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/zone2-inbox': typeof Zone2InboxIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/access-logs/': typeof AccessLogsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/de-identifier/': typeof DeIdentifierIndexRoute
  '/files/': typeof FilesIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rejections/': typeof RejectionsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/zone2-inbox/': typeof Zone2InboxIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/logs/$logId'
    | '/patients/new'
    | '/projects/$projectId'
    | '/roles/new'
    | '/users/new'
    | '/access-logs/'
    | '/applications/'
    | '/de-identifier/'
    | '/files/'
    | '/intake/'
    | '/logs/'
    | '/metadata/'
    | '/patients/'
    | '/projects/'
    | '/rejections/'
    | '/roles/'
    | '/users/'
    | '/zone2-inbox/'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/logs/$logId'
    | '/patients/new'
    | '/projects/$projectId'
    | '/roles/new'
    | '/users/new'
    | '/access-logs'
    | '/applications'
    | '/de-identifier'
    | '/files'
    | '/intake'
    | '/logs'
    | '/metadata'
    | '/patients'
    | '/projects'
    | '/rejections'
    | '/roles'
    | '/users'
    | '/zone2-inbox'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/applications/$applicationId'
    | '/logs/$logId'
    | '/patients/new'
    | '/projects/$projectId'
    | '/roles/new'
    | '/users/new'
    | '/access-logs/'
    | '/applications/'
    | '/de-identifier/'
    | '/files/'
    | '/intake/'
    | '/logs/'
    | '/metadata/'
    | '/patients/'
    | '/projects/'
    | '/rejections/'
    | '/roles/'
    | '/users/'
    | '/zone2-inbox/'
    | '/patients/$patientId/edit'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  LogsLogIdRoute: typeof LogsLogIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RolesNewRoute: typeof RolesNewRoute
  UsersNewRoute: typeof UsersNewRoute
  AccessLogsIndexRoute: typeof AccessLogsIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  DeIdentifierIndexRoute: typeof DeIdentifierIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MetadataIndexRoute: typeof MetadataIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RejectionsIndexRoute: typeof RejectionsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  Zone2InboxIndexRoute: typeof Zone2InboxIndexRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  RolesRoleIdEditRoute: typeof RolesRoleIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-logs/': {
      id: '/access-logs/'
      path: '/access-logs'
      fullPath: '/access-logs/'
      preLoaderRoute: typeof AccessLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-identifier/': {
      id: '/de-identifier/'
      path: '/de-identifier'
      fullPath: '/de-identifier/'
      preLoaderRoute: typeof DeIdentifierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId': {
      id: '/logs/$logId'
      path: '/logs/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/': {
      id: '/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof MetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejections/': {
      id: '/rejections/'
      path: '/rejections'
      fullPath: '/rejections/'
      preLoaderRoute: typeof RejectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone2-inbox/': {
      id: '/zone2-inbox/'
      path: '/zone2-inbox'
      fullPath: '/zone2-inbox/'
      preLoaderRoute: typeof Zone2InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId/edit': {
      id: '/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof RolesRoleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  LogsLogIdRoute: LogsLogIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RolesNewRoute: RolesNewRoute,
  UsersNewRoute: UsersNewRoute,
  AccessLogsIndexRoute: AccessLogsIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  DeIdentifierIndexRoute: DeIdentifierIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MetadataIndexRoute: MetadataIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RejectionsIndexRoute: RejectionsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  Zone2InboxIndexRoute: Zone2InboxIndexRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  RolesRoleIdEditRoute: RolesRoleIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
