/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsLogIdRouteImport } from './routes/logs/$logId'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers/$customerId.edit'
import { Route as CustomersCustomerIdFilesRouteImport } from './routes/customers/$customerId.files'
import { Route as RolesRoleIdEditRouteImport } from './routes/roles/$roleId.edit'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdRoute = LogsLogIdRouteImport.update({
  id: '/logs/$logId',
  path: '/logs/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/customers/$customerId/edit',
  path: '/customers/$customerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdFilesRoute =
  CustomersCustomerIdFilesRouteImport.update({
    id: '/customers/$customerId/files',
    path: '/customers/$customerId/files',
    getParentRoute: () => rootRouteImport,
  } as any)
const RolesRoleIdEditRoute = RolesRoleIdEditRouteImport.update({
  id: '/roles/$roleId/edit',
  path: '/roles/$roleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/customers/new': typeof CustomersNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId/files': typeof CustomersCustomerIdFilesRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/customers/new': typeof CustomersNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/logs': typeof LogsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId/files': typeof CustomersCustomerIdFilesRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/customers/new': typeof CustomersNewRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/customers/$customerId/files': typeof CustomersCustomerIdFilesRoute
  '/roles/$roleId/edit': typeof RolesRoleIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/customers/new'
    | '/logs/$logId'
    | '/roles/new'
    | '/users/new'
    | '/customers/'
    | '/logs/'
    | '/roles/'
    | '/users/'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/files'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/customers/new'
    | '/logs/$logId'
    | '/roles/new'
    | '/users/new'
    | '/customers'
    | '/logs'
    | '/roles'
    | '/users'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/files'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/customers/new'
    | '/logs/$logId'
    | '/roles/new'
    | '/users/new'
    | '/customers/'
    | '/logs/'
    | '/roles/'
    | '/users/'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/files'
    | '/roles/$roleId/edit'
    | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  CustomersNewRoute: typeof CustomersNewRoute
  LogsLogIdRoute: typeof LogsLogIdRoute
  RolesNewRoute: typeof RolesNewRoute
  UsersNewRoute: typeof UsersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  CustomersCustomerIdFilesRoute: typeof CustomersCustomerIdFilesRoute
  RolesRoleIdEditRoute: typeof RolesRoleIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId': {
      id: '/logs/$logId'
      path: '/logs/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/files': {
      id: '/customers/$customerId/files'
      path: '/customers/$customerId/files'
      fullPath: '/customers/$customerId/files'
      preLoaderRoute: typeof CustomersCustomerIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId/edit': {
      id: '/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof RolesRoleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  CustomersNewRoute: CustomersNewRoute,
  LogsLogIdRoute: LogsLogIdRoute,
  RolesNewRoute: RolesNewRoute,
  UsersNewRoute: UsersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  CustomersCustomerIdFilesRoute: CustomersCustomerIdFilesRoute,
  RolesRoleIdEditRoute: RolesRoleIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
